AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  users-api-cognito
  Sample SAM Template for photo-app-users-api-cognito

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        APP_CLIENT_ID: AQICAHj3XXenqbuqH/YuInNSnR5+QkNSQeCxfG/fxlVgREvo7gEZ6b50E8Ofhr75HD6iTBtiAAAAeDB2BgkqhkiG9w0BBwagaTBnAgEAMGIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgP3XZf+oY2gkZLs1AgEQgDVR//dbMy/pALuIOA1JxAN9I7oPpcrSZZiMUNcSOx/rdrK+6XHwqJKSBMsOHahBkzT6LRsdjg==
        APP_CLIENT_SECRET: AQICAHj3XXenqbuqH/YuInNSnR5+QkNSQeCxfG/fxlVgREvo7gERGB0cpS9jg7HtgqFcGN8mAAAAlDCBkQYJKoZIhvcNAQcGoIGDMIGAAgEAMHsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2gz0hxEtyPOJ/yjHAgEQgE6HP5vy1uFG84IjqmJuGL7aNvRfPj/FBqHz+teidSeG7xHMghQxBRSuWb/tYBMrbX15edGvWCIEeHvqOG3SImKMTuZc/Zn2+QM+VsNbHhw=


Resources:
  CreateUserHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: UsersApi
      Handler: com.jdlearner.users.handler.CreateUserHandler::handleRequest
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateUserApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateUserHandler Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CreateUserHandlerFunction:
    Description: "CreateUserHandler Lambda Function ARN"
    Value: !GetAtt CreateUserHandlerFunction.Arn
  CreateUserHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for CreateUserHandler"
    Value: !GetAtt CreateUserHandlerFunctionRole.Arn
